[package]
name = "pyslope"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module", "abi3-py37"] }
slope = { path = "../slope" }
git-version = "0.3.9"

[lib]
crate-type = ["cdylib"]

