[package]
name = "pyslope"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.24.0", features = ["extension-module", "abi3"] }
slope = { path = "../slope" }

[lib]
crate-type = ["cdylib"]

